name: ✨ Feature Request
description: Suggest a new feature for OMAP
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Summarize the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe how you'd like this feature to work...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Core Scanning Engine
        - Banner Grabbing / Service Detection
        - OS Fingerprinting
        - Target Management
        - Plugin System
        - Web Interface
        - Reconnaissance
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions you've considered
      placeholder: Describe any alternative solutions...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: Describe use cases...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any ideas on how this could be implemented?
      placeholder: Share implementation ideas...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
